apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w5mx2lvbl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w5mx2lvbl-nodejs 
  name: w5mx2lvbl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: w5mx2lvbl-nodejs 
